### ISSUE TITLE
Release.zip错误

### ISSUE THREAD

**Issue by Foglotus** [racherisgenius/Choudidi-rainbow-fart#1]
1.manifest.json文件,文件名拼写错误,拼成了mainfest.json
2.release包多了一层文件夹，导致无法使用官方接口导入

**Comment by racherisgenius** [comment]
> 1.manifest.json文件,文件名拼写错误,拼成了mainfest.json
> 2.release包多了一层文件夹，导致无法使用官方接口导入

哎呀，感谢指出！发现zip文件打包打了之前的一个文件！现在修改后应该好了
